### ISSUE TITLE
ｗｈｙ　ｙｏｕ　ｕｓｅｄ　－－ｒａｖｉ

### ISSUE THREAD

**Issue by KP1-cmd** [WenbinLee/DN4#13]
When** Ｉ　Try to run your code i get this error 
File　Not　Found　Error: [Errno 2] No such file or directory: '/Datasets/CubBirds--ravi/train.csv'
ｗｈａｔ　ｉｓ　ｒａｖｉ　ｉｎ　ｔｈａｔ？　ｗｈｙ　ｙｏｕ　ｕｓｅｄ　**ｒａｖｉ**　？
ｏｎｌｙ　instead　ｏｆ　**ｍｉｎｉＩｍａｇｅｎｅｔ**　ｉ　ｕｓｅｄ　**ｃｕｂ－200**

（parser.add_argument('--dataset_dir', default='/Datasets/miniImageNet--**ravi**', help='/miniImageNet')）

**Comment by Bryce1010** [comment]
What's the meaning of ravi?
I changed the dataset path to my local data address, it worked fine.

**Comment by WenbinLee** [comment]
Hi KP1-cmd, you may need to change the dataset path according to your own dir when you use this code. The ravi means we use the splits of miniImageNet provided by (Ravi and Larochelle 2017). Thank you.

Thanks, Bryce1010.

**Comment by KP1-cmd** [comment]
> Hi KP1-cmd, you may need to change the dataset path according to your own dir when you use this code. The ravi means we use the splits of miniImageNet provided by (Ravi and Larochelle 2017). Thank you.
> 
> Thanks, Bryce1010.

ok 
got it thank you ~
