### ISSUE TITLE
what about multiGPU training?

### ISSUE THREAD

**Issue by lerndeep** [WenbinLee/DN4#15]
I tried to train with multi GPU but I got error "expected batch size 34 target batch size 75" when I used 2 GPU?

**Comment by lerndeep** [comment]
how can I check which image file is classified correctly and which classified wrongly?

**Comment by WenbinLee** [comment]
Hi, you may also need to set "episodeSize" and "testepisodeSize" as 2 or 4 if you use 2 GPUs. Could you try it again?

**Comment by lerndeep** [comment]
yes, it is possible but GPU utilization is very low if we used multi GPU training. do you know any reason?

**Comment by lerndeep** [comment]
how can I check which image file is classified correctly and which classified wrongly?

**Comment by WenbinLee** [comment]
The main reason is that the implementation of our core algorithm is not very efficient. Maybe I can further revise this code to make it more efficient in the future (a couple of weeks). 

Actually, I am not really understand your second question. In fact, each image has a ground-truth label. In the datasets_csv.py, we will assign a random label for each image according to its ground-truth label, so you can check the correctness based on the assigned label (i.e., "target" in our code).
