### ISSUE TITLE
About preprocessing on Stanford_Cars

### ISSUE THREAD

**Issue by WeixiangXu** [WenbinLee/DN4#19]
Hi, thanks for your cool work. I have a question about Stanford_Cars.

I download all images of stanford_cars from `https://ai.stanford.edu/~jkrause/cars/car_dataset.html`.
The download file is as: car_ims/000001.jpg, 000002.jpg, ..., 016185.jpg
It seems that the provided [StanforCar_prepare_csv.py](https://github.com/WenbinLee/DN4/blob/c1d160e6241bf3482d06588be4a9fc87d3cfb932/dataset/StanforCar_prepare_csv.py) does not handle on this file?

Is there any other preprocess on the downloaded `car_ims`? Thanks!

**Comment by WenbinLee** [comment]
Hi, thanks for your interest in our work.

Yes, we have provided a preprocess script for processing the data, and you can find them in /DN4/dataset/StanforCar_prepare_csv.py. 

Thanks.

**Comment by WeixiangXu** [comment]
Thanks!
