### ISSUE TITLE
测试集 

### ISSUE THREAD

**Issue by nanxiaoting** [WenbinLee/DN4#2]
你好，训练的时候，就用测试集做验证，会不会导致模型提前见到这些数据，一直很苦恼这个问题

**Comment by WenbinLee** [comment]
不会呢，验证集和测试集的loss并没有用来反向回传，更新模型的参数。如果你不放心，可以在训练的时候去掉测试集。

**Comment by nanxiaoting** [comment]
谢谢你能这么快回复

**Comment by WenbinLee** [comment]
不客气呢
