### ISSUE TITLE
Question on paper figure

### ISSUE THREAD

**Issue by blondski** [WenbinLee/DN4#20]
Hi @WenbinLee ,
Great work. I'm writing a bachelor thesis on improving few-shot learning through data augmentation and it references your paper. Could I ask you to provide the code for plotting the following figures that you made in the paper. It would be very much appreciated!
![image](https://user-images.githubusercontent.com/57535992/235302796-1963339b-c4d4-4d36-90cd-0d1ac516ebdf.png)

**Comment by WenbinLee** [comment]
Hi Radu,

The attached Zip file is the MATLAB code of plotting the figures.
I Hope this helps.

Best,
Wenbin


---------------------------------------------------
Wenbin Li, PhD.

Assistant Professor
Department of Computer Science and Technology
State Key Laboratory for Novel Software Technology
Nanjing University, China

Email: ***@***.***; ***@***.*** ***@***.***>
Homepage: https://cs.nju.edu.cn/liwenbin/

**Comment by blondski** [comment]
Thank you
