### ISSUE TITLE
细粒度数据集准确率

### ISSUE THREAD

**Issue by jchuanHou** [WenbinLee/DN4#24]
作者您好！上次有关代码报错的issue非常感谢您能及时的回复，我是可以跑通backbone为Conv64F的模型的。
但是本周我在细粒度数据集**StanfordDogs**上重新跑了一下**2019版本的模型**，训练完毕以后经过测试发现5way1shot和5way5shot任务的准确率都比论文中的准确率有大幅度提高，但我并没有对代码进行修改，不知道这是什么情况呢？
backbone为Conv64F，论文中的5way1shot和5way5shot的准确率分别为45.41±0.76和63.51±0.62：
![image](https://github.com/WenbinLee/DN4/assets/115161445/7b22fd7d-1d65-4bc7-9705-20a21599cc9f)
我对该模型重新进行训练以及测试后，5way1shot和5way5shot的准确率分别为51.44和72.92：
![image](https://github.com/WenbinLee/DN4/assets/115161445/96a9e395-df1b-496d-ac68-7964f5f1a621)
![image](https://github.com/WenbinLee/DN4/assets/115161445/3e6562b0-01e2-4580-83f3-0e0f9549ae50)

**Comment by jchuanHou** [comment]
同时我也测试了CUB200的5way1shot和5way5shot的准确率分别为：64.78±0.87和84.35±0.57，比论文中的数据高了好多。
![image](https://github.com/WenbinLee/DN4/assets/115161445/8d773278-8dcf-4c8c-8b08-31202f5bf8ce)
![image](https://github.com/WenbinLee/DN4/assets/115161445/242b5c23-d998-42df-a200-8fcd39d6efd0)

**Comment by WenbinLee** [comment]
您好，确实遇到使用者提过类似的情况。这个可能是数据增广的影响，然后当时文章提交时并没有经过较好的调参。
---- 回复的原邮件 ----
***@***.***>发送日期2024年04月19日 08:28 ***@***.***> ***@***.***>主题Re: [WenbinLee/DN4] 细粒度数据集准确率 (Issue #24)
同时我也测试了CUB200的5way1shot和5way5shot的准确率分别为：64.78±0.87和84.35±0.57，比论文中的数据高了好多。
image.png (view on web)
image.png (view on web)

**Comment by jchuanHou** [comment]
好的，我明白了，非常感谢您能及时回复！
