### ISSUE TITLE
Could you please share your split csv files?

### ISSUE THREAD

**Issue by zihangJiang** [WenbinLee/DN4#3]
Hi. I'm really interested in your work, and I notice that the "os.listdir(images_dir)" is not sorted,
https://github.com/WenbinLee/DN4/blob/cb605fdf259549cb54ec51d09a53e7e762e7efa1/dataset/CubBird_prepare_csv.py#L32
so there might be some unexpected order here. Could you kindly share your csv files for verification?
Thanks in advance.

**Comment by WenbinLee** [comment]
Thank you very much. Yes, it's very important for a fair verification. I have already uploaded the splits of these three fine-grained datasets. 

Thanks.

**Comment by zihangJiang** [comment]
Thanks for your quick reply!
