### ISSUE TITLE
CUB

### ISSUE THREAD

**Issue by ken19950127** [WenbinLee/DN4#5]
您好，请问对于CUB数据集，epoch和miniImagenet一样还是30吗？因为感觉CUB数据集减少了。学习率衰减仍是10个epoch减一半吗？我对于参数调整不太敏感，希望收到作者的回复

**Comment by WenbinLee** [comment]
您好，我的实验中对于fine-trained的数据初始学习率是0.001，每10个epoch衰减为原来的1/20（即0.05），其实代码里面对miniImagenet用的衰减也是0.05倍，另外我没有对学习率进行细致地调参。

**Comment by ken19950127** [comment]
好的，谢谢你的回复

**Comment by WenbinLee** [comment]
不客气呢
